version: "3"
services:
  neo:
    container_name: Neo4j
    image: neo4j:4.0
    volumes:
      - data:/data
      - plugins:/plugins
      - import:/import
    ports:
      - "${DATABASE_HTTP}:7474"
      - "${DATABASE_BOLT}:7687"
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_AUTH=${DATABASE_USERNAME}/${DATABASE_PASSWORD}
    restart: unless-stopped

# use docker volume to persist data outside of a container.
volumes:
  data:
  plugins:
  import: